### PR TITLE
Fix Street Dealer Global Offset

### PR DESCRIPTION
**Pull request by L7NEG**
added local global_four_offset  = 6813

### CODE REVIEW

**Comment by L7NEG** [comment]
the paste in github file made it a lil bugged with empty spaces but the only change is the local global_four_offset  = 6813

**Comment by L7NEG** [comment]
After The Fix 
image
+ can i ask a permission from you to add your valuable work into next Ultimate Menu v2.2 update With Credits Included it is W feature fr

**Comment by L7NEG** [comment]
After The Fix 
image

**Comment by L7NEG** [comment]
oh i forgot this fix is same for the     active_vehicle              = globals.get_uint(global_three + global_four_offset + 3)

instead of     active_vehicle              = globals.get_uint(global_three + global_three_offset + 3) https://github.com/YimMenu-Lua/DailyCollectibles/commit/04be73fdfa901a3c56dc92c438f8af93e1f634a7

**Comment by L7NEG** [comment]
@ShinyWasabi and this too

**Comment by lhwe** [comment]
lmao 💀

**Comment by L7NEG** [comment]
See @lhwe that what I knew happened lol

**Pull request closed without merging**
